## For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED
kotlin.daemon.jvmargs=-Xmx1024m

android.useAndroidX=true
android.enableJetifier=false
android.jetifier.ignorelist=common-30.2.2.jar

# TODO : Migrate
android.nonTransitiveRClass=false

systemProp.https.protocols=TLSv1,TLSv1.1,TLSv1.2
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=true
android.r8.version=8.6.17
